# Generated by Django 2.0 on 2020-03-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ManyToManyField(blank=True, to='store.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carts',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='Contact Number')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.University')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profiles',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='wishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ManyToManyField(blank=True, to='store.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlists',
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
