# Generated by Django 2.0 on 2020-03-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignmentID', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('totalPair', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Shipped', 'Shipped'), ('On Route', 'On Route'), ('Delivered', 'Delivered'), ('Processing', 'Processing')], default='Shipped', max_length=20)),
                ('totalCommission', models.IntegerField(blank=True)),
                ('commissionPercentage', models.PositiveIntegerField(verbose_name='Commission Percentage')),
                ('totalPaid', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consignments',
                'verbose_name_plural': 'Consignments',
            },
        ),
        migrations.CreateModel(
            name='newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNo', models.CharField(max_length=15, verbose_name='Contact No')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Representatives',
                'verbose_name_plural': 'Representatives',
            },
        ),
        migrations.CreateModel(
            name='representativePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pushMoney', models.IntegerField()),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Approved', 'Approved')], default='Initiated', max_length=20)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.consignment')),
            ],
            options={
                'verbose_name': 'Representative Push',
                'verbose_name_plural': 'Representative Push',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=500)),
                ('collegeURL', models.URLField(max_length=1000)),
                ('collegeLocation', models.CharField(max_length=500)),
                ('collegeLocationURL', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'University',
            },
        ),
        migrations.AddField(
            model_name='representative',
            name='College',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.University'),
        ),
        migrations.AddField(
            model_name='representative',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consignment',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.representative'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.University'),
        ),
    ]
