# Generated by Django 2.0 on 2020-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200321_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fake_price',
            field=models.IntegerField(default=1200, verbose_name='Fake Price'),
        ),
    ]
